baseURL = '/' # Vercel will override this, but '/' is a safe default
languageCode = 'en-us'
title = 'Kids Bank'

# Disable kinds we don't need (optional, slight build speed improvement)
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT", "page", "section"]

[outputs]
  home = ["HTML"] # Only build HTML for the homepage (which we aren't really using)
  section = ["HTML"] # Only build HTML for sections like /transactions/

# We are using layouts/_default/list.html, so no theme is needed.
# theme = ""