name: Deploy Hugo Site to Homelab

on:
  push:
    branches:
      - main # Or your default branch (e.g., master)

jobs:
  build-and-deploy:
    # Target your self-hosted runner
    runs-on: self-hosted # Or use specific labels like [self-hosted, hugo-deployer]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for Hugo's GitInfo features if you use them

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build the image directly on the self-hosted runner
      # Tag it uniquely, e.g., with the Git SHA
      - name: Build Docker Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile # Assumes Dockerfile is in the root
          push: false # Don't push to a registry, just build locally on the runner
          tags: local-hugo-site:${{ github.sha }}
          load: true # Make the image available to the runner's Docker daemon

      # Stop and remove the existing container (if any)
      # Use a consistent container name for easy management
      - name: Stop and Remove Previous Container
        run: |
          docker stop hugo-site-container || true
          docker rm hugo-site-container || true
        continue-on-error: true # Ignore errors if the container doesn't exist

      # Run the new container with specified labels
      - name: Run New Container
        run: |
          docker run -d \
            --name hugo-site-container \
            --network proxy `# Connect to the 'proxy' network for Traefik` \
            --restart unless-stopped \
            `# --- Traefik and Watchtower Labels --- ` \
            -l "traefik.enable=true" \
            -l "traefik.http.routers.bank.entrypoints=http" \
            -l "traefik.http.routers.bank.rule=Host(`bank.local.solivan.dev`)" \
            -l "traefik.http.middlewares.bank-https-redirect.redirectscheme.scheme=https" \
            -l "traefik.http.routers.bank.middlewares=bank-https-redirect" \
            -l "traefik.http.routers.bank-secure.entrypoints=https" \
            -l "traefik.http.routers.bank-secure.rule=Host(`bank.local.solivan.dev`)" \
            -l "traefik.http.routers.bank-secure.tls=true" \
            -l "traefik.http.routers.bank-secure.service=bank" \
            -l "traefik.http.services.bank.loadbalancer.server.port=3000" `# <<< IMPORTANT: Service port is 3000` \
            -l "traefik.docker.network=proxy" \
            -l "com.centurylinklabs.watchtower.enable=true" `# <<< NOTE: Watchtower interaction` \
            `# --- End Labels --- ` \
            local-hugo-site:${{ github.sha }}

      # Optional: Clean up old images (be careful with this)