name: Build and Deploy Hugo Site

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  # Job 1: Build the Hugo site on GitHub's runners
  build:
    name: Build Hugo Site
    runs-on: ubuntu-latest # Use GitHub's runner for the build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for Hugo's GitInfo features if you use them
          submodules: true # Checkout submodules if your Hugo theme uses them

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3 # Action to install Hugo
        with:
          hugo-version: 'latest' # Or specify your Hugo version
          extended: true # Use Hugo extended version if needed

      - name: Build Hugo Site
        run: hugo --minify # Build site, output goes to ./public

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site-output # Name of the artifact
          path: public # Upload the 'public' directory

  # Job 2: Deploy the built site using your self-hosted runner
  deploy:
    name: Deploy to Homelab
    needs: build # Run this job only after the 'build' job succeeds
    runs-on: self-hosted # Use YOUR runner for deployment

    steps:
      - name: Checkout Code (for Dockerfile)
        uses: actions/checkout@v4
        # We only need the Dockerfile from the repo here

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: hugo-site-output # Must match the upload artifact name
          path: public # Download the artifact content into a directory named 'public'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        # Ensures buildx is available on your self-hosted runner

      # Build the SIMPLE Nginx image using Dockerfile and the downloaded 'public' directory
      - name: Build Deployment Image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: . # Build context includes Dockerfile.nginx and downloaded 'public' dir
          file: ./Dockerfile # Specify the correct Dockerfile
          push: false # Don't push to a registry
          tags: family-bank:${{ github.sha }} # Tag with commit SHA
          load: true # Load the image into the runner's Docker daemon

      # Stop and remove the existing container
      - name: Stop and Remove Previous Container
        run: |
          docker stop family-bank || true
          docker rm family-bank || true
        continue-on-error: true

# Run the new container - Adjusted for cross-host Traefik
      - name: Run New Container
        run: |
          docker run -d \
            --name family-bank \
            --restart unless-stopped \
            -p 8080:80 `# Map host port 8080 to container port 80 (adjust host port if needed)` \
            family-bank:${{ github.sha }}

      # Optional: Clean up old images if desired
      # - name: Prune old Docker images
      #   run: docker image prune -a -f --filter "until=24h"